import Foundation

enum AppRussianTranslations {
    static let table: [String: String] = [
        "0m": "0 мин",
        "A different iCloud account is now available. Choose whether to merge your local data into the current account, clear local synced data and download from iCloud again, or keep data local with automatic sync turned off.": "Теперь доступна другая учётная запись iCloud. Выберите: объединить локальные данные с текущей учётной записью, удалить локальные синхронизированные данные и заново загрузить их из iCloud, или оставить данные только на устройстве с отключённой автосинхронизацией.",
        "Add": "Добавить",
        "Added Date Ascending": "Дата добавления по возрастанию",
        "Added Date Descending": "Дата добавления по убыванию",
        "All": "Все",
        "Automatic Sync": "Автосинхронизация",
        "Background": "Фон",
        "Background Style": "Стиль фона",
        "Blue-White Gradient": "Сине-белый градиент",
        "Calendar Import": "Импорт календаря",
        "Cancel": "Отмена",
        "Category": "Категория",
        "Choose File": "Выбрать файл",
        "Choose whether to delete only this event or this event and all following events in the series.": "Выберите, удалить только это событие или это событие и все последующие в серии.",
        "Choose whether the changes apply only to this event or to this event and all following events in the series.": "Выберите, применить изменения только к этому событию или к этому событию и всем последующим в серии.",
        "Closed tasks keep their original time. You can still update the description, create a new task, or delete them.": "Закрытые задачи сохраняют исходное время. Вы по-прежнему можете изменить описание, создать новую задачу или удалить их.",
        "Complete": "Завершить",
        "Completed": "Завершено",
        "Completed At": "Завершено в",
        "Create New Task": "Создать новую задачу",
        "Custom": "Произвольно",
        "Day": "День",
        "Delete": "Удалить",
        "Delete Local Data and Resync": "Удалить локальные данные и синхронизировать заново",
        "Delete Task": "Удалить задачу",
        "Delete recurring task": "Удалить повторяющуюся задачу",
        "Delete this task?": "Удалить эту задачу?",
        "Deleting a subscription also removes the tasks imported from that URL.": "Удаление подписки также удалит задачи, импортированные по этому URL.",
        "Description": "Описание",
        "Detected a data conflict": "Обнаружен конфликт данных",
        "Detected an iCloud account change": "Обнаружено изменение учётной записи iCloud",
        "Display Options": "Параметры отображения",
        "Done": "Готово",
        "Edit Task": "Редактировать задачу",
        "Edit recurring task": "Редактировать повторяющуюся задачу",
        "End": "Окончание",
        "End Date": "Дата окончания",
        "End Repeat": "Завершить повтор",
        "End Time": "Время окончания",
        "Ended": "Завершено",
        "Every": "Каждые",
        "Every 2 Weeks": "Каждые 2 недели",
        "Every 2 weeks": "Раз в 2 недели",
        "Every Day": "Каждый день",
        "Every Month": "Каждый месяц",
        "Every Week": "Каждую неделю",
        "Every Year": "Каждый год",
        "Every day": "Каждый день",
        "Every month": "Каждый месяц",
        "Every week": "Каждую неделю",
        "Every year": "Каждый год",
        "Filter": "Фильтр",
        "Frequency Unit": "Единица периода",
        "Grid": "Сетка",
        "Grid View": "Вид сеткой",
        "Group List": "Список групп",
        "Group Name": "Название группы",
        "Groups": "Группы",
        "If an event in the feed has no start time, the import time is used as the start time. Future refreshes keep the first seen start time.": "Если у события в ленте нет времени начала, в качестве времени начала используется время импорта. При следующих обновлениях сохраняется первое обнаруженное время начала.",
        "If an imported event has no start time, the import time is used as the start time.": "Если у импортированного события нет времени начала, в качестве времени начала используется время импорта.",
        "Import Failed": "Не удалось импортировать",
        "Import Options": "Параметры импорта",
        "Import tasks from a standard .ics file.": "Импортировать задачи из стандартного файла .ics.",
        "In Progress": "В процессе",
        "Keep Cloud Data": "Оставить данные iCloud",
        "Keep Local Data": "Оставить локальные данные",
        "Language": "Язык",
        "Last attempted": "Последняя попытка",
        "Last synced": "Последняя синхронизация",
        "Legal": "Правовая информация",
        "Liquid Motion": "Жидкая анимация",
        "Mark as Completed": "Отметить как завершённую",
        "Mark as Incomplete": "Отметить как незавершённую",
        "Mark this task as completed?": "Отметить эту задачу как завершённую?",
        "Merge Local Data and Sync": "Объединить локальные данные и синхронизировать",
        "Month": "Месяц",
        "Motion": "Движение",
        "Never": "Никогда",
        "New Group": "Новая группа",
        "New Task": "Новая задача",
        "No URL subscriptions yet.": "Подписок по URL пока нет.",
        "No description": "Без описания",
        "No importable calendar events were found.": "Не найдено событий календаря для импорта.",
        "No items yet": "Пока нет задач",
        "Not Started": "Не начато",
        "Not synced yet": "Синхронизации ещё не было",
        "OK": "ОК",
        "Off": "Выкл.",
        "On": "Вкл.",
        "On Date": "В дату",
        "Pink-White Gradient": "Розово-белый градиент",
        "Please enter a valid URL.": "Введите корректный URL.",
        "Please keep at least one group.": "Оставьте хотя бы одну группу.",
        "Privacy Policy": "Политика конфиденциальности",
        "Progress Bar": "Индикатор прогресса",
        "Progress Bar View": "Вид с индикатором прогресса",
        "Pure White": "Чисто-белый",
        "Refresh All Subscriptions": "Обновить все подписки",
        "Refresh Subscriptions": "Обновить подписки",
        "Remaining Time Ascending": "Оставшееся время по возрастанию",
        "Remaining Time Descending": "Оставшееся время по убыванию",
        "Repeat": "Повтор",
        "Repeat Rule": "Правило повтора",
        "Save": "Сохранить",
        "Select File to Import": "Выберите файл для импорта",
        "Settings": "Настройки",
        "Start": "Начало",
        "Start Time": "Время начала",
        "Subscription": "Подписка",
        "Subscribe": "Подписаться",
        "Subscribe to an external calendar feed.": "Подписаться на внешний календарный канал.",
        "Subscriptions": "Подписки",
        "Sync": "Синхронизация",
        "Sync Content": "Содержимое синхронизации",
        "Sync Failed": "Сбой синхронизации",
        "Sync Options": "Параметры синхронизации",
        "Task Info": "Информация о задаче",
        "Tasks": "Задачи",
        "Tasks from URL subscriptions are refreshed by the feed. Change the source calendar or manage the subscription in Settings.": "Задачи из подписок по URL обновляются из ленты. Измените исходный календарь или управляйте подпиской в настройках.",
        "The URL is invalid.": "Некорректный URL.",
        "The calendar file could not be parsed.": "Не удалось разобрать файл календаря.",
        "The selected file could not be read.": "Не удалось прочитать выбранный файл.",
        "Time": "Время",
        "Title": "Название",
        "Title cannot be empty, and end time must be later than start time.": "Название не может быть пустым, а время окончания должно быть позже времени начала.",
        "Turn Off Automatic Sync": "Отключить автосинхронизацию",
        "Turn this on to sync data through iCloud on your Apple devices signed in to the same account.": "Включите это, чтобы синхронизировать данные через iCloud на ваших устройствах Apple, вошедших в одну и ту же учётную запись.",
        "Turning off group sync also turns off task and subscription sync.": "Отключение синхронизации групп также отключит синхронизацию задач и подписок.",
        "Untitled": "Без названия",
        "Use URL Subscription": "Использовать подписку по URL",
        "Week": "Неделя",
        "When off, liquid in the grid view no longer responds to device movement.": "Когда параметр выключен, жидкость в виде сетки больше не реагирует на движение устройства.",
        "Year": "Год",
    ]
}
